languages: typescript
files:
  - src/**/*
exclude:
  - src/*.ts
  - src/models/*.ts
  - src/service/index.ts
  - src/memoryModelsRepo/index.ts
  - src/mongoModelsRepo/index.ts
  - src/s3StorageRepo/index.ts
  - src/localStorageRepo/index.ts
  - src/serviceFactory/**/*.ts
  - src/repoFactory/**/*.ts
min-lines: 7
min-tokens: 50
debug: false
skip-comments: true
