language: node_js
node_js: node
sudo: false

notifications:
  email: false

env:
  global:
    - MONGODB=3.2.13
  matrix:
    - PACKAGE_MANAGER=yarn
    - PACKAGE_MANAGER=npm

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version

install:
  - if [ "$PACKAGE_MANAGER" == "npm" ]; then npm install; else yarn; fi

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
  - npm prune

script:
  - npm run build
  - npm run cover-ci
  - npm run lint -- -c tslint.travis.json
  - npm run duplication -- --limit=0.01

after_script:
  - pkill mongod

after_success:
  - npm run semantic-release
