version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: node:8.17.0@sha256:c4ea1d1f718962e98661a19f5bc2658e696a732a3f7e94ae2c79b93235bbc714
      - image: mongo:3.7.9@sha256:fbc5b316430a970543d2e1668164c764977e777a74ffb05c873d0e5df499b6fb
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
      - WINSTON_CONSOLE_LEVEL: none
      - EXPRESS_PORT: 1337
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Compiling Code
          command: npm run build
      - run:
          name: Running Tests
          command: npm run cover-ci
      - run:
          name: Linting Code
          command: npm run lint
      - deploy:
          name: Semantic Release
          command: npm run semantic-release
