version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: node:8.15.1@sha256:7898114f45abe72c66313af8ee713dd48a6993fbaa71502e3341546117cff170
      - image: mongo:3.7.9@sha256:736eec20a17eafaa988d299902fcaab521cb0ca56af4400f782576afc878d6bc
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
      - WINSTON_CONSOLE_LEVEL: none
      - EXPRESS_PORT: 1337
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Compiling Code
          command: npm run build
      - run:
          name: Running Tests
          command: npm run cover-ci
      - run:
          name: Linting Code
          command: npm run lint
      - deploy:
          name: Semantic Release
          command: npm run semantic-release
