name: Integration Suite

on: ['push']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  integrate:
    name: Integration
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_LOGLEVEL: warn
      WINSTON_CONSOLE_LEVEL: none
      EXPRESS_PORT: 1337
    
    services:
      mongo:
        image: mongo:3.7.9@sha256:736eec20a17eafaa988d299902fcaab521cb0ca56af4400f782576afc878d6bc
        env:
          NPM_CONFIG_LOGLEVEL: warn
          WINSTON_CONSOLE_LEVEL: none
          EXPRESS_PORT: 1337
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: 'npm'

      - name: Verify MySQL connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Installing Dependencies
        run: npm ci

      - name: Compiling Code
        run: npm run build

      - name: Running Tests
        run: npm run cover-ci

      - name: Linting Code
        run: npm run lint

      - name: Semantic Release
        if: github.ref == 'refs/heads/master'
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
