name: Integration Suite

on: ['push']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  integrate:
    name: Integration
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_LOGLEVEL: warn
      WINSTON_CONSOLE_LEVEL: none
      EXPRESS_PORT: 1337

    services:
      mongodb:
        image: mongo:3.7.9
        env:
          # MCLI_OPS_MANAGER_SKIP_VERIFY: yes
          # MCLI_SKIP_UPDATE_CHECK: yes
          # HTTP_PROXY: username:password@<my.proxy.address>
          # MONGO_INITDB_ROOT_USERNAME: root
          # MONGO_INITDB_ROOT_PASSWORD: root
          ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 27017
        options: --health-cmd="mongo" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: 'npm'

      # - name: Start MongoDB
      #   uses: supercharge/mongodb-github-action@1.2.0
      #   with:
      #     mongodb-version: 3.7.9

      - name: Installing Dependencies
        run: npm ci

      - name: Compiling Code
        run: npm run build

      - name: Running Tests
        run: npm run cover-ci

      - name: Linting Code
        run: npm run lint

      - name: Semantic Release
        if: github.ref == 'refs/heads/master'
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
